name: cafe_pay
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_svg: ^0.22.0
  email_validator: ^2.1.17
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_core_desktop: ^1.0.2
  flutter:
    sdk: flutter

  google_sign_in: ^5.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
