// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-1TGVWgDSyJE_L4gh4hgNg3owDmNXYmQ',
    appId: '1:57666365827:web:8a241d7721c17715fe6eb6',
    messagingSenderId: '57666365827',
    projectId: 'cafe-play-5908e',
    authDomain: 'cafe-play-5908e.firebaseapp.com',
    storageBucket: 'cafe-play-5908e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu6GGTWUsoEe_Zbu_BdGr0QHLa5DaP-Pg',
    appId: '1:57666365827:android:ec2d5e99fe0601d5fe6eb6',
    messagingSenderId: '57666365827',
    projectId: 'cafe-play-5908e',
    storageBucket: 'cafe-play-5908e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-1TGVWgDSyJE_L4gh4hgNg3owDmNXYmQ',
    appId: '1:57666365827:web:def6aca5760d87b6fe6eb6',
    messagingSenderId: '57666365827',
    projectId: 'cafe-play-5908e',
    authDomain: 'cafe-play-5908e.firebaseapp.com',
    storageBucket: 'cafe-play-5908e.appspot.com',
  );
}
